=== codeaudit/cougaar-robustness/Coordinator/src/org/cougaar/coordinator/techspec/AssetStateDTD.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT AssetStateDescriptors (AssetStates+) >
<!ELEMENT AssetStates (StateValues+,Transitions+) >
<!ATTLIST AssetStates
    stateName CDATA #REQUIRED
    assetType CDATA #REQUIRED
  >

<!ELEMENT StateValue EMPTY>
<!ATTLIST StateValue
    default CDATA #IMPLIED
    utility CDATA #REQUIRED
    name CDATA #REQUIRED
  >

<!ELEMENT StateValues (StateValue+)>

<!ELEMENT Transition EMPTY>
<!ATTLIST Transition
    startStateName CDATA #REQUIRED
    endStateName CDATA #REQUIRED
  >

<!ELEMENT Transitions (Transition+)>

=== codeaudit/cougaar-robustness/Coordinator/src/org/cougaar/coordinator/techspec/AssetStateXML.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE AssetStateDescriptors SYSTEM "AssetStateDTD.dtd">

<!-- Created by Paul Pazandak-->
<AssetStateDescriptors>
<AssetStates assetType="AGENT" stateName="Communication">
    <StateValues>
        <StateValue name="OK" utility="1" default="TRUE" />
        <StateValue name="NotCommunicating" utility="0" />
    </StateValues>
    <Transitions>
        <Transition startStateName="OK" endStateName="NotCommunicating"/>
        <Transition startStateName="NotCommunicating" endStateName="OK"/>
    </Transitions>
</AssetStates>
<AssetStates assetType="AGENT" stateName="Execution">
    <StateValues>
        <StateValue name="OK" utility="1" default="TRUE" />
        <StateValue name="Dead" utility="0" />
    </StateValues>
    <Transitions>
        <Transition startStateName="OK" endStateName="Dead"/>
    </Transitions>
</AssetStates>
<AssetStates assetType="NODE" stateName="PlannedDisconnect">
    <StateValues>
        <StateValue name="OK" utility="1" default="TRUE" />
        <StateValue name="Disconnected" utility="1" />
    </StateValues>
    <Transitions>
        <Transition startStateName="OK" endStateName="Disconnected"/>
        <Transition startStateName="Disconnected" endStateName="OK"/>
    </Transitions>
</AssetStates>
<AssetStates assetType="HOST" stateName="NetworkAccess">
    <StateValues>
        <StateValue name="OK" utility="1" default="TRUE" />
        <StateValue name="Goo" utility="0" />
    </StateValues>
    <Transitions>
        <Transition startStateName="OK" endStateName="Goo"/>
    </Transitions>
</AssetStates>

</AssetStateDescriptors>
