=== codeaudit/cougaar-robustness/Coordinator/src/org/cougaar/coordinator/techspec/DefenseXML_DTD.dtd
<?xml version='1.0' encoding='UTF-8'?>

<!--
    Typical usage:

    <?xml version="1.0"?>

    <!DOCTYPE DefenseXML SYSTEM "DefenseXML_DTD.dtd">

    <DefenseXML>
    ...
    </DefenseXML>
-->

<!ELEMENT Defense (Monitoring)+>
<!ATTLIST Defense
    tempBenefit CDATA #REQUIRED
    reversible CDATA #REQUIRED
    idempotent CDATA #REQUIRED
    tempCost CDATA #REQUIRED
    name CDATA #REQUIRED 
    abortable CDATA #REQUIRED
    assetType CDATA #REQUIRED
    affectsAssetState CDATA #REQUIRED
  >

<!ELEMENT DefenseXML (Defense)+>

<!ELEMENT DiagnosisAccuracy (Function)+>

<!ELEMENT Function EMPTY>
<!ATTLIST Function
    probability CDATA #REQUIRED
    diagnosis CDATA #REQUIRED
    assetType CDATA #IMPLIED
    assetStateValue CDATA #REQUIRED
    assetStateDescriptor CDATA #REQUIRED
  >

<!ELEMENT Level (DiagnosisAccuracy)*>
<!ATTLIST Level
    latency CDATA #REQUIRED
    cost CDATA #REQUIRED
    name CDATA #REQUIRED
  >

<!ELEMENT Monitoring (Level)+>

=== codeaudit/cougaar-robustness/Coordinator/src/org/cougaar/coordinator/techspec/DefenseXML.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE DefenseXML SYSTEM "DefenseXML_DTD.dtd">

<DefenseXML>
    <Defense name="SledgeHammer" assetType="AGENT" idempotent="TRUE" reversible="TRUE" 
             abortable="TRUE" tempCost="11" tempBenefit="5" affectsAssetState="EXECUTION" >
        <Monitoring>
            <Level name="NORMAL" latency="2000" cost="10">
                <DiagnosisAccuracy>
                    <Function diagnosis="Dead" assetStateDescriptor="EXECUTION" assetStateValue="Dead" probability="0.5" />
                    <Function diagnosis="Dead" assetStateDescriptor="EXECUTION" assetStateValue="OK" probability="0.4" />
                    <Function diagnosis="Dead" assetType="AGENT" assetStateDescriptor="COMMUNICATION" assetStateValue="NotCommunicating" probability="0.5" />
                </DiagnosisAccuracy>
            </Level>
        </Monitoring>
    </Defense>
</DefenseXML>
