=== codeaudit/cougaar-robustness/Coordinator/src/org/cougaar/coordinator/techspec/ThreatModelXML_DTD.dtd
<?xml version='1.0' encoding='UTF-8'?>

<!--
    Typical usage:
    <?xml version="1.0"?>
    <!DOCTYPE ThreatModelDef SYSTEM "ThreatModelXML_DTD.dtd">
    <ThreatModels>
    ...
    </ThreatModels>
-->

<!ELEMENT ThreatModels (ThreatModelDef+)>

<!ELEMENT DamageVector (Distribution+)>
<!ELEMENT Distribution (Transition+)>
<!ATTLIST Distribution
    name CDATA #REQUIRED
  >

<!ELEMENT Filter EMPTY>
<!ATTLIST Filter
    op CDATA #REQUIRED
    propName CDATA #REQUIRED
    propValue CDATA #REQUIRED
    propType CDATA #REQUIRED
  >

<!ELEMENT MemberFilters (Filter+)>

<!ELEMENT ThreatModelDef (DamageVector+, MemberFilters*, Likelihood+ )>
<!ATTLIST ThreatModelDef
    assetType CDATA #REQUIRED
    threatType CDATA #REQUIRED
    name CDATA #REQUIRED
  >

<!ELEMENT Likelihood (ApplicabilityInterval+) >

<!ELEMENT ApplicabilityInterval EMPTY >

<!ATTLIST ApplicabilityInterval
    probability CDATA #REQUIRED
    period CDATA #REQUIRED
    intervalLength CDATA #REQUIRED
  >

<!ELEMENT Transition EMPTY>
<!ATTLIST Transition
    probability CDATA #REQUIRED
    startState CDATA #REQUIRED
    endState CDATA #REQUIRED
  >

=== codeaudit/cougaar-robustness/Coordinator/src/org/cougaar/coordinator/techspec/ThreatModelXML.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE ThreatModels SYSTEM "ThreatModelXML_DTD.dtd">

<ThreatModels>
<ThreatModelDef name="CommFailure" assetType="AGENT" threatType="CommunicationFailure">
<DamageVector>
        <Distribution name="Communication">
              <Transition 
                    startState="OK" 
                    endState="NotCommunicating" 
                    probability="0.01"/>
              <Transition 
                    startState="NotCommunicating" 
                    endState="OK" 
                    probability="0.25"/>
        </Distribution>
    </DamageVector>
    <!--MemberFilters>
        <Filter propName="location" propValue="KANSAS" op="=" propType="S"></Filter>
        <Filter propName="mobile" propValue="TRUE" op="=" propType="S" ></Filter>
    </MemberFilters -->
    <Likelihood>
        <ApplicabilityInterval period="ALWAYS" intervalLength="30" probability="1.0" />
    </Likelihood>
</ThreatModelDef>
<ThreatModelDef name="SledgeHammer" assetType="AGENT" threatType="AgentCrash">
    <DamageVector>
        <Distribution name="Execution">
              <Transition 
                    startState="OK" 
                    endState="Dead" 
                    probability="0.001"/>
              <Transition 
                    startState="Dead" 
                    endState="OK" 
                    probability="0.0"/>
        </Distribution>
    </DamageVector>
    <Likelihood>
        <ApplicabilityInterval period="ALWAYS" intervalLength="3600" probability="0.25" />
    </Likelihood>
</ThreatModelDef>
<ThreatModelDef name="FWDNodeDisconnect" assetType="NODE" threatType="PlannedDisconnect">
    <DamageVector>
        <Distribution name="PlannedDisconnect">
              <Transition 
                    startState="OK" 
                    endState="Disconnected" 
                    probability="0.01"/>
              <Transition 
                    startState="Disconnected" 
                    endState="OK" 
                    probability="0.9"/>
        </Distribution>
    </DamageVector>
    <MemberFilters>
        <Filter propName="LOCATION" propValue="FORWARD" op="=" propType="S" ></Filter>
    </MemberFilters>
    <Likelihood>
        <ApplicabilityInterval period="ALWAYS" intervalLength="3600" probability="0.5" />
    </Likelihood>
</ThreatModelDef>
<ThreatModelDef name="REARNodeDisconnect" assetType="NODE" threatType="PlannedDisconnect">
    <DamageVector>
        <Distribution name="PlannedDisconnect">
              <Transition 
                    startState="OK" 
                    endState="Disconnected" 
                    probability="0.0001"/>
              <Transition 
                    startState="Disconnected" 
                    endState="OK" 
                    probability="0.999"/>
        </Distribution>
    </DamageVector>
    <MemberFilters>
        <Filter propName="LOCATION" propValue="REAR" op="=" propType="S" ></Filter>
    </MemberFilters>
    <Likelihood>
        <ApplicabilityInterval period="ALWAYS" intervalLength="3600" probability="0.1" />
    </Likelihood>
</ThreatModelDef>
</ThreatModels>
