<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Communities [
<!ELEMENT Communities (Community+)>
<!ELEMENT Community (Attribute*, Entity*)>
<!ATTLIST Community Name CDATA #REQUIRED>
<!ELEMENT Entity (Attribute*)>
<!ATTLIST Entity Name CDATA #REQUIRED>
<!ELEMENT Attribute EMPTY>
<!ATTLIST Attribute ID CDATA #REQUIRED>
<!ATTLIST Attribute Value CDATA #REQUIRED>
]>
<Communities>
  <!--********************************************************
      *                                                      *
      *  1 A D  -  S M A L L  -  C O M M                     *
      *                                                      *
      ********************************************************-->
  <Community Name="1AD-SMALL-COMM" >
    <Attribute ID="CommunityType"             Value="Robustness" />
    <Attribute ID="CommunityManager"          Value="ARManager" />
    <!-- Defines name of Robustness Manager node agent -->
    <Attribute ID="RobustnessManager"         Value="ARManager" />
    <!-- Number of agents expected to join community.  Robustness manager
         will generate a "Community Ready" CougaarEvent when the
         number of active agents in the community hits this level.  -->
    <Attribute ID="NumberOfAgents"            Value="60" />
    <!-- Parameter values used by Robustness Manager.  Parameters set for
         Entities override these values -->
    <Attribute ID="INITIAL_EXPIRATION"        Value="180000" />
    <Attribute ID="LOCATED_EXPIRATION"        Value="120000" />
    <Attribute ID="ACTIVE_EXPIRATION"         Value="120000" />
    <Attribute ID="HEALTH_CHECK_EXPIRATION"   Value="240000" />
    <Attribute ID="DEAD_EXPIRATION"           Value="30000" />
    <Attribute ID="RESTART_EXPIRATION"        Value="300000" />
    <Attribute ID="FAILED_RESTART_EXPIRATION" Value="30000" />
    <Attribute ID="MOVE_EXPIRATION"           Value="300000" />
    <Attribute ID="PING_TIMEOUT"              Value="120000" />
    <Attribute ID="HEARTBEAT_REQUEST_TIMEOUT" Value="60000" />
    <Attribute ID="HEARTBEAT_FREQUENCY"       Value="60000" />
    <Attribute ID="HEARTBEAT_TIMEOUT"         Value="90000" />
    <Attribute ID="HEARTBEAT_PCT_OUT_OF_SPEC" Value="80" />
    <!-- Nodes -->
    <Entity Name="FWD-NODE" >
      <Attribute ID="EntityType" Value="Node" />
      <Attribute ID="Role" Value="Member" />
      <Attribute ID="Role" Value="HealthMonitor" />
    </Entity>
    <Entity Name="REAR-NODE" >
      <Attribute ID="EntityType" Value="Node" />
      <Attribute ID="Role" Value="Member" />
      <Attribute ID="Role" Value="HealthMonitor" />
    </Entity>
    <Entity Name="TRANS-NODE" >
      <Attribute ID="EntityType" Value="Node" />
      <Attribute ID="Role" Value="Member" />
      <Attribute ID="Role" Value="HealthMonitor" />
    </Entity>
    <!-- AR Manager -->
    <Entity Name="ARManager" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
      <Attribute ID="Role" Value="HealthMonitor" />
      <Attribute ID="Role" Value="RobustnessManager" />
    </Entity>
    <!-- FWD -->
    <Entity Name="1-35-ARBN" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <Entity Name="1-6-INFBN" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <Entity Name="1-AD" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <Entity Name="102-POL-SUPPLYCO" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <Entity Name="123-MSB" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <Entity Name="47-FSB" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <Entity Name="123-MSB" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <Entity Name="16-CSG" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <Entity Name="18-MAINTBN" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <Entity Name="2-BDE-1-AD" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <Entity Name="227-SUPPLYCO" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <Entity Name="26-SSCO" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <Entity Name="485-CSB" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <Entity Name="DISCOM-1-AD" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <!-- REAR -->
    <Entity Name="1-27-FABN" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <Entity Name="110-POL-SUPPLYCO" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <Entity Name="125-ORDBN" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <Entity Name="130-ENGBDE" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <Entity Name="191-ORDBN" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <Entity Name="21-TSC-HQ" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <Entity Name="240-SSCO" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <Entity Name="29-SPTGP" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <Entity Name="3-SUPCOM-HQ" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <Entity Name="316-POL-SUPPLYBN" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <Entity Name="343-SUPPLYCO" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <Entity Name="37-TRANSGP" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <Entity Name="41-FABDE" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <Entity Name="5-CORPS" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <Entity Name="5-CORPS-ARTY" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <Entity Name="5-CORPS-REAR" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <Entity Name="51-MAINTBN" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <Entity Name="52-ENGBN-CBTHVY" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <Entity Name="565-RPRPTCO" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <Entity Name="574-SSCO" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <Entity Name="592-ORDCO" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <Entity Name="597-MAINTCO" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <Entity Name="6-TCBN" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <Entity Name="7-CSG" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <Entity Name="561-SSBN" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <Entity Name="200-MMC" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <Entity Name="226-MAINTCO" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <Entity Name="632-MAINTCO" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <Entity Name="406-SUPPLYCO" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <Entity Name="71-MAINTBN" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <Entity Name="900-POL-SUPPLYCO" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <Entity Name="AWR-2" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <Entity Name="DLAHQ" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <Entity Name="FORSCOM" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <Entity Name="HNS" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <Entity Name="NCA" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <Entity Name="OSC" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <Entity Name="USAEUR" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <Entity Name="USEUCOM" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <!-- TRANSCOM -->
    <Entity Name="TRANSCOM" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <Entity Name="CONUSGround" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <Entity Name="GlobalAir" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <Entity Name="GlobalSea" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <Entity Name="PlanePacker" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <Entity Name="ShipPacker" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <Entity Name="TRANSCOM" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <Entity Name="TheaterGround" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <!-- <Entity Name="NestedCommunity1" >
      <Attribute ID="EntityType" Value="Community" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <Entity Name="NestedCommunity2" >
      <Attribute ID="EntityType" Value="Community" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
    <Entity Name="NestedCommunity3" >
      <Attribute ID="EntityType" Value="Community" />
      <Attribute ID="Role" Value="Member" />
    </Entity> -->
  </Community>
  <!-- <Community Name="NestedCommunity1" >
    <Attribute ID="CommunityType" Value="Test" />
    <Entity Name="TheaterGround" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
  </Community>
  <Community Name="NestedCommunity2" >
    <Attribute ID="CommunityType" Value="Test" />
    <Entity Name="TRANSCOM" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
  </Community>
  <Community Name="NestedCommunity3" >
    <Attribute ID="CommunityType" Value="Test" />
    <Entity Name="ShipPacker" >
      <Attribute ID="EntityType" Value="Agent" />
      <Attribute ID="Role" Value="Member" />
    </Entity>
  </Community> -->
</Communities>
