=== codeaudit/cougaar-robustness/Coordinator/configs/coordinator/MappingDTD.dtd
<?xml encoding="UTF-8" ?>

<!-- Created by Administrator on July 5, 2004, 10:55 AM -->

<!ELEMENT Map (Mapping+)>

<!ELEMENT Mapping EMPTY>
<!ATTLIST Mapping
    name CDATA #REQUIRED
    value CDATA #REQUIRED
>


<!-- * <Map>
 *   <Mapping name="LOW" value="0"/>
 *   <Mapping name="MEDIUM" value="1"/>
 *   ...
 * </Map> 
-->

=== codeaudit/cougaar-robustness/Coordinator/configs/coordinator/ProbabilityMap.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE Map SYSTEM "MappingDTD.dtd">

<Map>
   <Mapping name="VERY_LOW"  value=".1" />
   <Mapping name="LOW"       value=".3" />
   <Mapping name="MEDIUM"    value=".5" />
   <Mapping name="HIGH"      value=".7" />
   <Mapping name="VERY_HIGH" value=".9" />
   <Mapping name="ALWAYS"    value="1" />
   <Mapping name="NONE"      value="0" />
</Map>
