=== codeaudit/cougaar-robustness/Coordinator/test/LatestINIs/AssetStateDimensionsDTD.dtd
<?xml encoding="UTF-8" ?>

<!-- Created by Administrator on March 22, 2004, 8:54 AM -->

<!ELEMENT AssetStateDimensions (StateDimension+) > 
<!ATTLIST AssetStateDimensions
    assetType CDATA #REQUIRED
>

<!ELEMENT StateDimension (SimpleState+) >
<!ATTLIST StateDimension
    name CDATA #REQUIRED
>
  
<!ELEMENT SimpleState EMPTY>
<!ATTLIST SimpleState
    name CDATA #REQUIRED
    defaultStartState CDATA #IMPLIED
    relativeMauCompleteness CDATA #REQUIRED
    relativeMauSecurity CDATA #REQUIRED
>
  

<!-- Example
<AssetStateDimensions assetType=“Agent”>
    <StateDimension name=“LIVENESS” >
        <SimpleState name=”LIVE" defaultStartState=”TRUE” relativeMauCompleteness=”1.0” relativeMauSecurity=”1.0” />
        <SimpleState name=”DEAD" relativeMauCompleteness=”0.0” relativeMauSecurity=”1.0” />
    </StateDimension>

    <StateDimension name=“COMMUNICATION” >
        <SimpleState name=“GOOD” defaultStartState=”TRUE” relativeMauCompleteness=”1.0” relativeMauSecurity=”1.0” />
        <SimpleState name=”DEGRADED” relativeMauCompleteness=”0.5” relativeMauSecurity=”0.9” />
        <SimpleState name=”PLANNED_DISCONNECT” relativeMauCompleteness=”0.3” relativeMauSecurity=”1.0” />
    </StateDimension>
</AssetStateDimensions>
-->

=== codeaudit/cougaar-robustness/Coordinator/test/LatestINIs/TestDTD_AgentStateDim.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE AssetStateDimensions SYSTEM "AssetStateDimensionsDTD.dtd" >

<AssetStateDimensions assetType="Agent">

  <StateDimension name="Communication" >
 	<SimpleState name="Communicating" relativeMauCompleteness="0.9" 
                                    relativeMauSecurity="0.5"
			            defaultStartState="TRUE" />

 	<SimpleState name="Degraded" relativeMauCompleteness="0.5" 
                               relativeMauSecurity="0.5" />

 	<SimpleState name="Planned_Disconnect" relativeMauCompleteness="0.9" 
	                                 relativeMauSecurity="1.0" />

 	<SimpleState name="Not_Communicating" relativeMauCompleteness="0.0" 
                                        relativeMauSecurity="0.5" />

  </StateDimension>

  <StateDimension name="Liveness" >
 	<SimpleState name="Live" relativeMauCompleteness="1.0" 
                         relativeMauSecurity="0.5"
 		         defaultStartState="TRUE" />
 	<SimpleState name="Dead" relativeMauCompleteness="0.0" 
                           relativeMauSecurity="0.5" />

  </StateDimension>

  <StateDimension name="Encryption" >
 	<SimpleState name="256_bit" relativeMauCompleteness="0.5" 
                           relativeMauSecurity="1.0"
			   defaultStartState="TRUE" />
 	<SimpleState name="128_bit" relativeMauCompleteness="0.7"
	                     relativeMauSecurity="0.7" />
 	<SimpleState name="64_bit" relativeMauCompleteness="0.5"
	                     relativeMauSecurity="0.5" />
 	<SimpleState name="None" relativeMauCompleteness="0.5"
	                   relativeMauSecurity="0.1" />

  </StateDimension>

  <StateDimension name="Eavesdropping" >
 	<SimpleState name="None" relativeMauCompleteness="0.5" 
                           relativeMauSecurity="1.0"
			   defaultStartState="TRUE" />
 	<SimpleState name="Low" relativeMauCompleteness="0.7"
	                     relativeMauSecurity="0.7" />
 	<SimpleState name="Medium" relativeMauCompleteness="0.5"
	                     relativeMauSecurity="0.5" />
 	<SimpleState name="High" relativeMauCompleteness="0.5"
	                   relativeMauSecurity="0.1" />

  </StateDimension>

</AssetStateDimensions>
