=== codeaudit/cougaar-robustness/Coordinator/src/org/cougaar/coordinator/techspec/xml/ActuatorTypeDTD.dtd
<?xml version="1.0" encoding="UTF-8" ?>


<!ELEMENT ActuatorType (Action*) >
<!ATTLIST ActuatorType 
    name CDATA #REQUIRED
    affectsAssetType CDATA #REQUIRED
    affectsStateDimension CDATA #REQUIRED
>

<!ELEMENT Action (Description, Transition+)  >
<!ATTLIST Action 
    name CDATA #REQUIRED
>

<!ELEMENT Description EMPTY  >
<!ATTLIST Description 
    value CDATA #REQUIRED
>

<!ELEMENT Transition (OneTimeCost? , ContinuingCost? )  >
<!ATTLIST Transition
    WhenActualStateIs CDATA #REQUIRED
    EndStateWillBe CDATA #REQUIRED
>

<!ELEMENT OneTimeCost (Bandwidth?, CPU?, Memory?, Time? ) >
<!ELEMENT ContinuingCost (Bandwidth?, CPU?, Memory?, Time? ) >

<!ELEMENT CPU EMPTY> 
<!ATTLIST CPU
    intensity ( NONE | VERY_LOW | LOW | MEDIUM | HIGH | VERY_HIGH ) 'NONE'
    agentSizeFactor  (TRUE | FALSE) 'FALSE'
    msgSizeFactor  (TRUE | FALSE) 'FALSE'
>

<!ELEMENT Bandwidth EMPTY> 
<!ATTLIST Bandwidth
    intensity ( NONE | VERY_LOW | LOW | MEDIUM | HIGH | VERY_HIGH ) 'NONE'
    agentSizeFactor  (TRUE | FALSE) 'FALSE'
    msgSizeFactor  (TRUE | FALSE) 'FALSE'
>

<!ELEMENT Memory EMPTY> 
<!ATTLIST Memory
    intensity ( NONE | VERY_LOW | LOW | MEDIUM | HIGH | VERY_HIGH ) 'NONE'
    agentSizeFactor  (TRUE | FALSE) 'FALSE'
    msgSizeFactor  (TRUE | FALSE) 'FALSE'
>

<!ELEMENT Time EMPTY> 
<!ATTLIST Time
    duration CDATA #REQUIRED
>

<!-- example
<ActuatorType name="RestartAgent" affectsAssetType="Agent" affectsStateDimension="Liveness" >
    <Action name="LocalRestart">
        <Description value="Restarts agent in node on local host" />
        <Transition WhenActualStateIs="*" EndStateWillBe="LIVE" >
            <OneTimeCost>
                <CPU intensity="HIGH" agentSizeFactor="TRUE" />
            </OneTimeCost>
            <ContinuingCost>
                <CPU intensity="MEDIUM" msgSizeFactor="TRUE" />
            </ContinuingCost>
        </Transition>
    </Action>
    
    <Action name="QuickRemoteRestart">
        <Description value="Restarts agent in first available node" />
        <Transition WhenActualStateIs="*" EndStateWillBe="LIVE" >
            <OneTimeCost>
                <Bandwidth intensity="MEDIUM" agentSizeFactor="TRUE" />
                <CPU intensity="HIGH" agentSizeFactor="TRUE" />
            </OneTimeCost>
        </Transition>
    </Action>

    <Action name="BalancingRestart">
        <Description value="Restarts multiple agents with a rebalancing plan" />
        <Transition WhenActualStateIs="*" EndStateWillBe="LIVE" >
            <OneTimeCost>
                <Bandwidth intensity="MEDIUM" agentSizeFactor="TRUE" />
                <CPU intensity="HIGH" agentSizeFactor="TRUE" />
                <Time duration="120" />
            </OneTimeCost>
        </Transition>
    </Action>
</ActuatorType>
-->

=== codeaudit/cougaar-robustness/msglog/configs/coordinator/msglog/MsglogActions.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE ActuatorType SYSTEM "ActuatorTypeDTD.dtd">

<ActuatorType name="org.cougaar.mts.std.LinksEnablingAction" 
              affectsAssetType="Agent" 
              affectsStateDimension="MsglogSetting" 
              actionType="COMPENSATORY">

    <Action name="SuppressCommunications">
        <Description value="Suppresses attempts to communicate" />
        <Transition WhenActualStateIs="*" EndStateWillBe="SuppressCommunications" IntermediateStateWillBe="SuppressCommunications" >
            <OneTimeCost>
                <Time duration="100" />
            </OneTimeCost>
        </Transition>
    </Action>
    
    <Action name="Normal">
        <Description value="Tries Normal RMI Communications only" />
        <Transition WhenActualStateIs="*" EndStateWillBe="NormalRMIProtocol" IntermediateStateWillBe="SuppressCommunications" >
            <OneTimeCost>
                <Time duration="100" />
            </OneTimeCost>
            <ContinuingCost>
                <Bandwidth intensity="LOW" msgSizeFactor="TRUE" />
            </ContinuingCost>
        </Transition>
    </Action>

    <Action name="AlternateDirectProtocols">
        <Description value="Adds other Direct Protocols to RMI" />
        <Transition WhenActualStateIs="*" EndStateWillBe="AlternateDirectProtocols" IntermediateStateWillBe="SuppressCommunications">
            <OneTimeCost>
                <Time duration="100" />
            </OneTimeCost>
            <ContinuingCost>
                <Bandwidth intensity="LOW" msgSizeFactor="TRUE" />
	          <CPU intensity="LOW" msgSizeFactor="TRUE" />
            </ContinuingCost>
        </Transition>
    </Action>

    <Action name="StoreAndForwardProtocols">
        <Description value="Adds the use of Store and Forward Protocols" />
        <Transition WhenActualStateIs="*" EndStateWillBe="StoreAndForwardProtocols" IntermediateStateWillBe="SuppressCommunications" >
            <OneTimeCost>
                <Time duration="1000" />
            </OneTimeCost>
            <ContinuingCost>
                <Bandwidth intensity="MEDIUM" msgSizeFactor="TRUE" />
	          <CPU intensity="MEDIUM" msgSizeFactor="TRUE" />
            </ContinuingCost>
        </Transition>
    </Action>

</ActuatorType>

=== codeaudit/cougaar-robustness/Coordinator/configs/coordinator/Sledgehammer/Restart_RestartActuator.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE ActuatorType SYSTEM "ActuatorTypeDTD.dtd">

<ActuatorType name="org.cougaar.coordinator.test.defense.RestartAgentDefense" 
              affectsAssetType="Agent" 
              affectsStateDimension="Liveness" 
              actionType="CORRECTIVE">
    <Action name="Yes">
        <Description value="Restart Enabled" />
        <Transition WhenActualStateIs="*" EndStateWillBe="Live" IntermediateStateWillBe="Dead" >
            <OneTimeCost>
                <CPU intensity="HIGH" agentSizeFactor="TRUE" />
                <Time duration="60000" />
            </OneTimeCost>
            <ContinuingCost>
                <CPU intensity="MEDIUM" msgSizeFactor="TRUE" />
            </ContinuingCost>
        </Transition>
    </Action>
    
    <Action name="No">
        <Description value="Restart Disabled - Does nothing and costs nothing" />
        <Transition WhenActualStateIs="Live" EndStateWillBe="Live"  IntermediateStateWillBe="Live"/>
        <Transition WhenActualStateIs="Dead" EndStateWillBe="Dead"  IntermediateStateWillBe="Dead"/>
    </Action>

</ActuatorType>

=== codeaudit/cougaar-robustness/Coordinator/configs/coordinator/LeashDefenses/LeashDefenses_LeashActuator.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE ActuatorType SYSTEM "ActuatorTypeDTD.dtd">

<ActuatorType name="org.cougaar.coordinator.unleashDefenses.LeashAction" 
              affectsAssetType="Enclave" 
              affectsStateDimension="DefenseSuppression" 
              actionType="CORRECTIVE">

    <Action name="Leash">
        <Description value="Suppress all Defense Actions (except this one)" />
        <Transition WhenActualStateIs="Leashed" EndStateWillBe="Leashed" IntermediateStateWillBe="Leashed" >
            <OneTimeCost>
                <CPU intensity="VERY_LOW" />
                <Time duration="100" />
            </OneTimeCost>
        </Transition>
        <Transition WhenActualStateIs="Unleashed" EndStateWillBe="Unleashed" IntermediateStateWillBe="Unleashed" >
            <OneTimeCost>
                <CPU intensity="VERY_LOW" />
                <Time duration="100" />
            </OneTimeCost>
        </Transition>
        <Transition WhenActualStateIs="WantsToLeash" EndStateWillBe="WantsToLeash" IntermediateStateWillBe="Leashed" >
            <OneTimeCost>
                <CPU intensity="VERY_LOW" />
                <Time duration="100" />
            </OneTimeCost>
        </Transition>
        <Transition WhenActualStateIs="WantsToUnleash" EndStateWillBe="WantsToUnleash" IntermediateStateWillBe="WantsToUnleash" >
            <OneTimeCost>
                <CPU intensity="VERY_LOW" />
                <Time duration="100" />
            </OneTimeCost>
        </Transition>
    </Action>

    <Action name="Unleash">
        <Description value="Make all Defenses under consideration for enabling " />
        <Transition WhenActualStateIs="Leashed" EndStateWillBe="Leashed" IntermediateStateWillBe="Leashed" >
            <OneTimeCost>
                <CPU intensity="VERY_LOW" />
                <Time duration="100" />
            </OneTimeCost>
        </Transition>
        <Transition WhenActualStateIs="Unleashed" EndStateWillBe="Unleashed" IntermediateStateWillBe="Unleashed" >
            <OneTimeCost>
                <CPU intensity="VERY_LOW" />
                <Time duration="100" />
            </OneTimeCost>
        </Transition>
        <Transition WhenActualStateIs="WantsToLeash" EndStateWillBe="WantsToLeash" IntermediateStateWillBe="WantsToLeash" >
            <OneTimeCost>
                <CPU intensity="VERY_LOW" />
                <Time duration="100" />
            </OneTimeCost>
        </Transition>
        <Transition WhenActualStateIs="WantsToUnleash" EndStateWillBe="WantsToUnleash" IntermediateStateWillBe="Unleashed" >
            <OneTimeCost>
                <CPU intensity="VERY_LOW" />
                <Time duration="100" />
            </OneTimeCost>
        </Transition>
    </Action>

</ActuatorType>

=== codeaudit/cougaar-robustness/Coordinator/configs/coordinator/SampleDefense_SampleActuator.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE ActuatorType SYSTEM "ActuatorTypeDTD.dtd">

<ActuatorType name="org.cougaar.coordinator.examples.SampleDefense.SampleAction" 
              affectsAssetType="Agent" 
              affectsStateDimension="Compromised" 
              actionType="CORRECTIVE">

    <Action name="Quarantine">
        <Description value="Quarantine the Agent so it can do no harm" />
        <Transition WhenActualStateIs="Yes" EndStateWillBe="Isolated" IntermediateStateWillBe="Yes" >
            <OneTimeCost>
                <CPU intensity="MEDIUM" />
                <Memory intensity="MEDIUM" />
                <Time duration="60000" />
            </OneTimeCost>
            <ContinuingCost>
                <Bandwidth intensity="MEDIUM" msgSizeFactor="TRUE" />
                <CPU intensity="MEDIUM" msgSizeFactor="TRUE" />
            </ContinuingCost>
        </Transition>
        <Transition WhenActualStateIs="No" EndStateWillBe="Isolated" IntermediateStateWillBe="No" >
            <OneTimeCost>
                <CPU intensity="MEDIUM" />
                <Memory intensity="MEDIUM" />
                <Time duration="60000" />
            </OneTimeCost>
            <ContinuingCost>
                <Bandwidth intensity="MEDIUM" msgSizeFactor="TRUE" />
                <CPU intensity="MEDIUM" msgSizeFactor="TRUE" />
            </ContinuingCost>
        </Transition>
        <Transition WhenActualStateIs="Isolated" EndStateWillBe="Isolated" IntermediateStateWillBe="Isolated" >
            <OneTimeCost>
                <CPU intensity="MEDIUM" />
                <Memory intensity="MEDIUM" />
                <Time duration="60000" />
            </OneTimeCost>
            <ContinuingCost>
                <Bandwidth intensity="MEDIUM" msgSizeFactor="TRUE" />
                <CPU intensity="MEDIUM" msgSizeFactor="TRUE" />
            </ContinuingCost>
        </Transition>
    </Action>

    <Action name="Release">
        <Description value="Release the (presumably sanitized) Agent so it can do work" />
        <Transition WhenActualStateIs="Yes" EndStateWillBe="Yes" IntermediateStateWillBe="Yes" >
            <OneTimeCost>
                <CPU intensity="MEDIUM" />
                <Memory intensity="MEDIUM" />
                <Time duration="60000" />
            </OneTimeCost>
        </Transition>
        <Transition WhenActualStateIs="No" EndStateWillBe="No" IntermediateStateWillBe="No" >
            <OneTimeCost>
                <CPU intensity="MEDIUM" />
                <Memory intensity="MEDIUM" />
                <Time duration="60000" />
            </OneTimeCost>
        </Transition>
        <Transition WhenActualStateIs="Isolated" EndStateWillBe="No" IntermediateStateWillBe="Isolated" >
            <OneTimeCost>
                <CPU intensity="MEDIUM" />
                <Memory intensity="MEDIUM" />
                <Time duration="60000" />
            </OneTimeCost>
        </Transition>
    </Action>
    
</ActuatorType>

=== codeaudit/cougaar-robustness/Coordinator/configs/coordinator/MsgLog/MsgLog_MsgLogActuator.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE ActuatorType SYSTEM "ActuatorTypeDTD.dtd">

<ActuatorType name="org.cougaar.coordinator.test.defense.MsgLogActuator" 
              affectsAssetType="Agent" 
              affectsStateDimension="MsgLogSetting" 
              actionType="Compensatory">

    <Action name="Suppress_Communications">
        <Description value="Suppresses attempts to communicate" />
        <Transition WhenActualStateIs="*" EndStateWillBe="Suppress_Communications" IntermediateStateWillBe="Suppress_Communications" >
            <OneTimeCost>
                <Time duration="100" />
            </OneTimeCost>
        </Transition>
    </Action>
    
    <Action name="Normal">
        <Description value="Tries Normal RMI Communications only" />
        <Transition WhenActualStateIs="*" EndStateWillBe="Normal_RMI_Protocol" IntermediateStateWillBe="Suppress_Communications" >
            <OneTimeCost>
                <Time duration="100" />
            </OneTimeCost>
            <ContinuingCost>
                <Bandwidth intensity="LOW" bandwidthSIzeFactor="TRUE" />
            </ContinuingCost>
        </Transition>
    </Action>

    <Action name="Alternate_Direct_Protocols">
        <Description value="Adds other Direct Protocols to RMI" />
        <Transition WhenActualStateIs="*" EndStateWillBe="Alternate_Direct_Protocols" IntermediateStateWillBe="Suppress_Communications">
            <OneTimeCost>
                <Time duration="100" />
            </OneTimeCost>
            <ContinuingCost>
                <Bandwidth intensity="LOW" bandwidthSIzeFactor="TRUE" />
	          <CPU intensity="LOW" bandwidthSIzeFactor="TRUE" />
            </ContinuingCost>
        </Transition>
    </Action>

    <Action name="Store_And_Forward_Protocols">
        <Description value="Adds the use of Store and Forward Protocols" />
        <Transition WhenActualStateIs="*" EndStateWillBe="Store_And_Forward_Protocols" IntermediateStateWillBe="Suppress_Communications" >
            <OneTimeCost>
                <Time duration="1000" />
            </OneTimeCost>
            <ContinuingCost>
                <Bandwidth intensity="MEDIUM" bandwidthSIzeFactor="TRUE" />
	          <CPU intensity="MEDIUM" bandwidthSIzeFactor="TRUE" />
            </ContinuingCost>
        </Transition>
    </Action>

</ActuatorType>
