=== codeaudit/cougaar-robustness/Coordinator/src/org/cougaar/coordinator/techspec/xml/SensorTypeDTD.dtd
<?xml encoding="UTF-8" ?>

<!-- Created by Administrator on March 24, 2004, 11:34 AM -->

<!ELEMENT SensorType (PotentialDiagnoses, Diagnoses) >
<!ATTLIST SensorType 
    name CDATA #REQUIRED
    sensesAssetType CDATA #REQUIRED
    sensesStateDimension CDATA #REQUIRED
    sensorLatency CDATA #REQUIRED
>

<!ELEMENT PotentialDiagnoses (Diagnosis+) >

<!ELEMENT Diagnosis >
<!ATTLIST Diagnosis 
    name CDATA #REQUIRED
>

<!ELEMENT Diagnoses (WhenActualStateIs+) >

<!ELEMENT WhenActualStateIs (WillDiagnoseAs+) >
<!ATTLIST WhenActualStateIs 
    name CDATA #REQUIRED
>

<!ELEMENT WillDiagnoseAs >
<!ATTLIST WillDiagnoseAs 
    name CDATA #REQUIRED
    withProbability CDATA #REQUIRED
>


<!-- Example
<SensorType name="AgentCommunication" sensesAssetType="Agent" sensesStateDimension=”COMMUNICATION” sensorLatency=”1000”>
    <PotentialDiagnoses>
        <Diagnosis name=”OK” />
        <Diagnosis name=”DEGRADED” />
        <Diagnosis name=”NOT_COMMUNICATING” />
    </PotentialDiagnoses>
    <Diagnoses>
        <WhenActualStateIs name=”GOOD” >
            <WillDiagnoseAs name=”OK” withProbability=”0.9” />
            <WillDiagnoseAs name=”DEGRADED” withProbability=”0.1” />
        </WhenActualStateIs >
        <WhenActualStateIs name=”DEGRADED” >
            <WillDiagnoseAs name=”OK” withProbability=”0.1” />
            <WillDiagnoseAs name=”DEGRADED” withProbability=”0.8” />
            <WillDiagnoseAs name=”NOT_COMMUNICATING” withProbability=”0.1” />
        </WhenActualStateIs >
        <WhenActualStateIs name=”PLANNED_DISCONNECT” >
            <WillDiagnoseAs name=”DEGRADED” withProbability=”0.01” />
            <WillDiagnoseAs name=”NOT_COMMUNICATING” withProbability=”0.99” />
        </WhenActualStateIs >
        <WhenActualStateIs name=”NOT_COMMUNICATING” >
            <WillDiagnoseAs name=”DEGRADED” withProbability=”0.01” />
            <WillDiagnoseAs name=”NOT_COMMUNICATING” withProbability=”0.99” />
        </WhenActualStateIs >
    </Diagnoses>
</SensorType>

-->

=== codeaudit/cougaar-robustness/mgmt_agent/configs/coordinator/Restart_LivenessSensor.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE SensorType  SYSTEM "SensorTypeDTD.dtd" >

<SensorType name="org.cougaar.tools.robustness.ma.util.AgentLivenessDiagnosis"
            sensesAssetType="Agent"
            sensesStateDimension="Liveness"
            sensorLatency="30000"
		reportingPolicy="ALWAYS_CURRENT" >
    <PotentialDiagnoses>
        <Diagnosis name="Live" defaultValue="TRUE" />
        <Diagnosis name="Dead" />
    </PotentialDiagnoses>
    <Diagnoses>
        <WhenActualStateIs name="Live" >
            <WillDiagnoseAs name="Live" withProbability="0.99" />
            <WillDiagnoseAs name="Dead" withProbability="0.01" />
        </WhenActualStateIs >
        <WhenActualStateIs name="Dead" >
            <WillDiagnoseAs name="Dead" withProbability="0.99" />
            <WillDiagnoseAs name="Live" withProbability="0.01" />
        </WhenActualStateIs >
    </Diagnoses>
</SensorType>

=== codeaudit/cougaar-robustness/Coordinator/configs/coordinator/SampleDefense/SampleDefense_SampleSensor.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE SensorType SYSTEM "SensorTypeDTD.dtd" >

<SensorType name="org.cougaar.coordinator.examples.SampleDefense.SampleDiagnosis" 
            sensesAssetType="Agent"
            sensesStateDimension="Compromised" 
            sensorLatency="1000">
    <PotentialDiagnoses>
        <Diagnosis name="Compromised" />
        <Diagnosis name="Secure" defaultValue="TRUE" />
        <Diagnosis name="Isolated" />
    </PotentialDiagnoses>
    <Diagnoses>
        <WhenActualStateIs name="Yes" >
            <WillDiagnoseAs name="Secure" withProbability="0.4" />
            <WillDiagnoseAs name="Compromised" withProbability="0.6" />
        </WhenActualStateIs >
        <WhenActualStateIs name="No" >
            <WillDiagnoseAs name="Secure" withProbability="0.9" />
            <WillDiagnoseAs name="Compromised" withProbability="0.1" />
        </WhenActualStateIs >
        <WhenActualStateIs name="Isolated" >
            <WillDiagnoseAs name="Isolated" withProbability="1.0" />
        </WhenActualStateIs >
    </Diagnoses>
</SensorType>

=== codeaudit/cougaar-robustness/Coordinator/configs/coordinator/Sledgehammer/Restart_LivenessSensor.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE SensorType  SYSTEM "SensorTypeDTD.dtd" >

<SensorType name="org.cougaar.coordinator.examples.RestartDefense.RestartDiagnosis" 
            sensesAssetType="Agent"
            sensesStateDimension="Liveness" 
		sensorLatency="120000">
    <PotentialDiagnoses>
        <Diagnosis name="Live" />
        <Diagnosis name="Dead" />
    </PotentialDiagnoses>
    <Diagnoses>
        <WhenActualStateIs name="Live" >
            <WillDiagnoseAs name="Live" withProbability="0.99" />
            <WillDiagnoseAs name="Dead" withProbability="0.01" />
        </WhenActualStateIs >
        <WhenActualStateIs name="Dead" >
            <WillDiagnoseAs name="Dead" withProbability="0.99" />
            <WillDiagnoseAs name="Live" withProbability="0.01" />
        </WhenActualStateIs >
    </Diagnoses>
</SensorType>

=== codeaudit/cougaar-robustness/Coordinator/configs/coordinator/LeashDefenses/LeashDefenses_LeashSensor.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE SensorType SYSTEM "SensorTypeDTD.dtd" >

<SensorType name="org.cougaar.coordinator.leashDefenses.LeashRequestDiagnosis" 
            sensesAssetType="Enclave"
            sensesStateDimension="DefenseSuppression" 
            sensorLatency="10">
    <PotentialDiagnoses>
        <Diagnosis name="LeashRequest" />
        <Diagnosis name="UnleashRequest" />
        <Diagnosis name="NoRequest" defaultValue="TRUE" />
    </PotentialDiagnoses>
    <Diagnoses>
        <WhenActualStateIs name="WantsToUnleash" >
            <WillDiagnoseAs name="UnleashRequest" withProbability="1.0" />
        </WhenActualStateIs >
        <WhenActualStateIs name="WantsToUnLeash" >
            <WillDiagnoseAs name="LeashRequest" withProbability="1.0" />
        </WhenActualStateIs >
        <WhenActualStateIs name="Leashed" >
            <WillDiagnoseAs name="NoRequest" withProbability="1.0" />
        </WhenActualStateIs >
        <WhenActualStateIs name="Unleashed" >
            <WillDiagnoseAs name="NoRequest" withProbability="1.0" />
        </WhenActualStateIs >
    </Diagnoses>
</SensorType>
