=== codeaudit/cougaar-robustness/Coordinator/src/org/cougaar/coordinator/techspec/xml/ThreatDTD.dtd
<?xml encoding="UTF-8" ?>

<!-- Created by Administrator on March 24, 2004, 11:32 AM -->

<!ELEMENT Threats (Threat+)>
<!ELEMENT Threat (VulnerableAssets*)>

<!ATTLIST Threat
    name CDATA #REQUIRED
    affectsAssetType CDATA #REQUIRED
    causesEvent CDATA #REQUIRED
    defaultEventLikelihoodProb ( NONE | VERY_LOW | LOW | MEDIUM | HIGH | VERY_HIGH | ALWAYS ) 'NONE'
    probIntervalInMins CDATA #REQUIRED
>

<!ELEMENT VulnerableAssets (AssetFilter, (EventLikelihoodInterval|EventLikelihood)?) >

<!ELEMENT AssetFilter (Term | CorruptHostExistsOnNetwork | CorruptHostExists)+ >
<!ELEMENT EventLikelihoodInterval (ClockInterval)+ >

<!ELEMENT EventLikelihood  EMPTY>
<!ATTLIST EventLikelihood
    probability ( NONE | VERY_LOW | LOW | MEDIUM | HIGH | VERY_HIGH | ALWAYS ) 'NONE'
    probIntervalInMins CDATA #REQUIRED
>

<!ELEMENT ClockInterval  EMPTY>
<!ATTLIST ClockInterval
    intervalStart CDATA #REQUIRED
    durationHrs CDATA #REQUIRED
    probability ( NONE | VERY_LOW | LOW | MEDIUM | HIGH | VERY_HIGH | ALWAYS ) 'NONE'
    probIntervalInMins CDATA #REQUIRED
>

<!ELEMENT Term EMPTY>
<!ATTLIST Term
    propName CDATA #REQUIRED
    propValue CDATA #REQUIRED
    op ( GT | GE | LT | LE | EQ | NE) 'EQ' 
    propType ( S | L | D | I ) "S"
>
<!-- propType = [S]tring [L]ong [D]ouble [I]nteger       op ( &lt; | &gt; | &gt;= | &lt;= | = | != ) '=' -->

<!ELEMENT CorruptHostExistsOnNetwork EMPTY >
<!ATTLIST CorruptHostExistsOnNetwork
    value CDATA #REQUIRED
>
<!ELEMENT CorruptHostExists EMPTY >
<!ATTLIST CorruptHostExists
    value CDATA #REQUIRED
>

<!-- Example
<Threat name="Bomb" affectsAssetType="Host" causesEvent="HostDeath" defaultEventLikelihoodProb="NONE" probIntervalInMins=1000 />

    <VulnerableAssets>
        <AssetFilter>
            <Term propName="location" propValue="HiWay" op="=" />
        </AssetFilter >
        <EventLikelihoodInterval>
            <ClockInterval intervalStart="1800" durationHrs="12" probability="VERY_LOW" probIntervalInMins=1000 />
        </EventLikelihoodInterval>
    </VulnerableAssets>

    <VulnerableAssets>
        <AssetFilter>
            <Term propName="location" propValue="OffRoad" op="=" />
        </AssetFilter>
        <EventLikelihoodInterval>
            <ClockInterval intervalStart="1800" durationHrs="12" probability="MEDIUM" probIntervalInMins=1000 />
            <ClockInterval intervalStart="1800" durationHrs="12" probability="LOW" probIntervalInMins=1000 />
        </EventLikelihoodInterval>
    </VulnerableAssets>

</Threat>

Some variations:
 
<AssetFilter>
    <CorruptHostExistsOnNetwork value="TRUE" />    
</AssetFilter >
 
<AssetFilter>
    <CorruptHostExists value="TRUE" />    
</AssetFilter >
 
 
-->

=== codeaudit/cougaar-robustness/mgmt_agent/configs/coordinator/Restart_Threats.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE Threats SYSTEM "ThreatDTD.dtd"   >
<Threats>
<Threat name="Bomb" affectsAssetType="Host" causesEvent="HostDeath" defaultEventLikelihoodProb="NONE" probIntervalInMins="1000" >

    <VulnerableAssets>
        <AssetFilter>
            <Term propName="location" propValue="HiWay" op="EQ" />
        </AssetFilter>
        <EventLikelihoodInterval>
            <ClockInterval intervalStart="1800" durationHrs="12" probability="VERY_LOW" probIntervalInMins="1000" />
        </EventLikelihoodInterval>
    </VulnerableAssets>

    <VulnerableAssets>
        <AssetFilter>
            <Term propName="location" propValue="OffRoad" op="EQ" />
        </AssetFilter>
        <EventLikelihoodInterval>
            <ClockInterval intervalStart="1800" durationHrs="12" probability="MEDIUM" probIntervalInMins="1000" />
            <ClockInterval intervalStart="0600" durationHrs="12" probability="LOW" probIntervalInMins="1000" />
        </EventLikelihoodInterval>
    </VulnerableAssets>

    <VulnerableAssets>
	  <AssetFilter>
           <CorruptHostExistsOnNetwork value="TRUE" />    
	  </AssetFilter>
        <EventLikelihood probability="LOW" probIntervalInMins="1000" />
    </VulnerableAssets>

    <VulnerableAssets>
	  <AssetFilter>
           <CorruptHostExists value="TRUE" />    
	  </AssetFilter>
        <EventLikelihood probability="HIGH" probIntervalInMins="1000" />
    </VulnerableAssets>

</Threat>

<Threat name="AgentVirus" affectsAssetType="Agent" causesEvent="AgentDeath" defaultEventLikelihoodProb="MEDIUM" probIntervalInMins="100" />

<Threat name="NodeVirus" affectsAssetType="Node" causesEvent="NodeDeath" defaultEventLikelihoodProb="VERY_LOW" probIntervalInMins="1000" />


</Threats>
