<?xml version="1.0" encoding="UTF-8" ?>

<!-- Created by Administrator on April 5, 2004, 11:09 AM -->

<!DOCTYPE Event [

<!ELEMENT Event (DirectEffect, TransitiveEffect) >

<!ELEMENT DirectEffect (Transition+) >

<!ELEMENT Transition EMPTY >
<!ATTLIST Transition
    WhenActualStateIs CDATA #REQUIRED
    EndStateWillBe    CDATA #REQUIRED
>

<!ELEMENT TransitiveEffect (CausesEvent, VulnerableAssets) >

<!ELEMENT CausesEvent EMPTY >
<!ATTLIST CausesEvent
    name       CDATA #REQUIRED
    assetType  CDATA #REQUIRED
>

<!ELEMENT VulnerableAssets (ContainmentFilter, EventLikelihood) >

<!ELEMENT EventLikelihood  EMPTY>
<!ATTLIST EventLikelihood
    probability ( NONE | VERY_LOW | LOW | MEDIUM | HIGH | VERY_HIGH ) 'NONE'
>

<!ELEMENT ContainmentFilter  EMPTY>
<!ATTLIST ContainmentFilter
    eventAssetContainerName CDATA #REQUIRED
>

]>

<Events>
<Event name="HostDeath" affectsAssetType="Host" affectsStateDimension="Liveness">
    <DirectEffect>
        <Transition WhenActualStateIs="*" EndStateWillBe="DEAD" />
    </DirectEffect>
    <TransitiveEffect>
        <CausesEvent name="NodeDeath" assetType="Node"/>
        <VulnerableAssets>
            <ContainmentFilter eventAssetContainerName="Node" />
            <EventLikelihood probability="ALWAYS" />
        </VulnerableAssets>
    </TransitiveEffect> 
</Event>
<Event name="HostDeath2" affectsAssetType="Host" affectsStateDimension="Liveness">
    <DirectEffect>
        <Transition WhenActualStateIs="Eating" EndStateWillBe="DEAD" />
        <Transition WhenActualStateIs="Sleeping" EndStateWillBe="DEAD" />
    </DirectEffect>
    <TransitiveEffect>
        <CausesEvent name="NodeDeath" assetType="Node"/>
        <VulnerableAssets>
            <ContainmentFilter eventAssetContainerName="Node" />
            <EventLikelihood probability="ALWAYS" />
        </VulnerableAssets>
    </TransitiveEffect> 
</Event>
</Events>